services:
  - type: web
    name: uniyo-cloud
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: gunicorn cloud_server:app
