services:
  - type: web
    name: uniyo-cloud
    runtime: python
    runtimeVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cloud_server:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
