services:
  - type: web
    name: uniyo-lms
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 init_database.py && gunicorn cloud_server:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
